name: C/C++ CI Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_clang:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.0
      with:
        submodules: true 
    - name: Install packages
      run: sudo apt-get update && sudo apt-get install ninja-build libsdl2-dev doxygen libtbb-dev
    - name: Clang Build
      uses: LightningCreations/action-cmake-build@v1.2
      with:
        cc: clang
        cxx: clang++
        update-submodules: true
        parallel: 8
        build-dir: ${{github.workspace}}/build-clang 
        build-type: Release
        configure-options: -GNinja
  build_gcc:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.0
      with:
        submodules: true 
    - name: Install packages
      run: sudo apt-get update && sudo apt-get install ninja-build libsdl2-dev libtbb-dev
    - name: GCC Build
      uses: LightningCreations/action-cmake-build@v1.2
      with:
        cc: gcc
        cxx: g++
        update-submodules: true
        parallel: 8
        build-dir: ${{github.workspace}}/build-gcc 
        build-type: Release
        configure-options: -GNinja
