name: C/C++ CI OSX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_macos:
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.0
        with:
          submodules: true
      - name: Install packages
        run: brew install ninja
      - name: Clang Build
        uses: LightningCreations/action-cmake-build@v1.2
        with:
          cc: clang
          cxx: clang++
          update-submodules: true
          parallel: 8
          build-dir: ${{github.workspace}}/build-macos
          build-type: Release
          configure-options: -GNinja
