name: C/C++ CI Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.0
        with:
          submodules: true
      - name: Install packages
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install llvm ninja ccache
      - name: Get Clang
        run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
      - name: Clang Build
        uses: LightningCreations/action-cmake-build@v1.2
        with:
          cc: clang
          cxx: clang++
          update-submodules: true
          parallel: 8
          build-dir: ${{github.workspace}}/build-windows
          build-type: Release
          configure-options: -GNinja
